spring:
  application:
    name: eureka
server:
  port: 9999

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl.defaultZone: http://localhost:9999/eureka/
    registerWithEureka: false
    fetchRegistry: false
